version: "3.9"
services:
    mariadb:
        container_name: MariaDB
        image: mariadb:latest
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-vol:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        restart: always

volumes:
    db-vol:
        driver: local