version: "3.9"
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres-vol:/var/lib/postgres
        ports:
            - ${DB_PORT}:5432
        restart: always

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8080:80
        environment:
        - PMA_ARBITRARY=1

volumes:
    postgres-vol:
        driver: local
